LIST P=16F887
#include "p16f887.inc"

	W_TEMP		EQU	0x20
	STATUS_TEM	EQU	0x21
	
	ORG	0x00
	GOTO	INICIO
	ORG	0x04
	GOTO	ISR
	ORG	0x05
	
INICIO
	BSF	STATUS, RP0
	BSF	STATUS, RP1
	BCF	ANSELH, ANS12	    ;MODO DIGITAL RB4
	BCF	ANSELH, ANS12	    ;MODO DIGITAL RB5
				    ;LOS PINES RB6 Y RB7 UNICAMENTE FUNCIONAN DE MANERA DIGITAL, NO HACE FALTA SETEARLOS
	BCF	STATUS, RP1
	MOVLW	b'11110000'
	MOVWF	TRISB
	BCF	OPTION_REG, INTEDG  ;SETEO DE ACCION POR FLANCO DE BAJADA
	BCF	OPTION_REG, RBPU    ;ACTIVO LAS RESISTENCIAS PULL-UP PARA LOS PINES DEL PUERTO B
	BCF	INTCON, RBIF	    ;SETEO COMO QUE NO HUBIERON CAMBIOS EN NINGUN PIN DEL PUERTO B
	BSF	INTCON, INTE
	BSF	INTCON, GIE
	BCF	STATUS, RP0
	
LOOP	GOTO	LOOP
	
ISR
	;SALVADO CONTEXTO-----------------------
	MOVWF	W_TEMP
	SWAPF	STATUS, W
	MOVWF	STATUS_TEMP
	
	;CODIGO ISR ----------------------------

	
	
	
	
	
	;RECONSTRUCCION CONTEXTO----------------
	SWAPF	STATUS_TEMP, W
	MOVWF	STATUS
	SWAPF	W_TEMP, F
	SWAPF	W_TEMP, W
	RETFIE				    ;COLOCADO PARA LEVANTAR EL GIE Y RECIBIR OTRA INTERRUPCION


