LIST P=16F887
#include "p16f887.inc"

	CBLOCK	0x20
		W_TEMP
		STATUS_TEMP
		COUNT_TMRO
	ENDC
	
	ORG	0x00
	GOTO	INICIO
	ORG	0x04
	GOTO	ISR
	ORG	0x05

CONF_PUERTOS	MACRO
	BSF	STATUS, RP0
	BSF	STATUS, RP1
	BCF	ANSELH, ANS12	    ;MODO DIGITAL RB4
	BCF	ANSELH, ANS12	    ;MODO DIGITAL RB5
				    ;LOS PINES RB6 Y RB7 UNICAMENTE FUNCIONAN DE MANERA DIGITAL, NO HACE FALTA SETEARLOS
	BCF	STATUS, RP1
	MOVLW	b'11110000'
	MOVWF	TRISB
	BCF	OPTION_REG, INTEDG  ;SETEO DE ACCION POR FLANCO DE BAJADA
	BCF	OPTION_REG, RBPU    ;ACTIVO LAS RESISTENCIAS PULL-UP PARA LOS PINES DEL PUERTO B
	BCF	INTCON, RBIF	    ;SETEO COMO QUE NO HUBIERON CAMBIOS EN NINGUN PIN DEL PUERTO B
	BSF	INTCON, INTE
	BSF	INTCON, GIE
	BCF	STATUS, RP0
ENDM
	
CONF_TMRO	MACRO
	BANKSEL OPTION_REG
	MOVLW	b'00000111'
	MOVWF	OPTION_REG
	BANKSEL	TMR0
	MOVLW	.61
	MOVWF	TMR0
ENDM
	
INICIO
	CONF_PUERTOS
	CONF_TMRO
	
LOOP	GOTO	LOOP
	
ISR
	;SALVADO CONTEXTO-----------------------
	MOVWF	W_TEMP
	SWAPF	STATUS, W
	MOVWF	STATUS_TEMP
	
	;CODIGO ISR ----------------------------
	BANKSEL	PORTB
	BCF	PORTB, RB3
	BTFSC	INTCON, T0IF
	GOTO	IRO_CONF
	GOTO	ISR_FIN
	
IRO_CONF
	INCF	COUNT_TMRO, F
	MOVLW	.250
	SUBWF	COUNT_TMRO, W
	BTFSS	STATUS, Z
	GOTO	ISR_TMRO
	GOTO	ISR_LED_ON
	
ISR_TMRO
	MOVLW	.61
	MOVWF	TMR0
	GOTO	ISR_LED_ON
	
ISR_LED_ON
	BCF	INTCON, TOIF
	BCF	INTCON, RBIF
	BANKSEL	PORTB
	BSF	PORTB,	RB3
	
	;RECONSTRUCCION CONTEXTO----------------
	SWAPF	STATUS_TEMP, W
	MOVWF	STATUS
	SWAPF	W_TEMP, F
	SWAPF	W_TEMP, W
	RETFIE				    ;COLOCADO PARA LEVANTAR EL GIE Y RECIBIR OTRA INTERRUPCION

END