;Encabezado
LIST P=16F887
#include "p16f887.inc"
    
;DEFINICION VARIABLES

    CBLOCK	0x20
	    W_TEM
	    STATUS_TEMP
	    NTecla
	    COUNT_TMRO
    ENDC
    
;INICIO MICRO
    
    ORG		0x00
    GOTO	INICIO
    ORG		0x04
    GOTO	IST_INICIO
    ORG		0x05
    
;CONFIGURACION PUERTOS (TECL+DSPL)
    
CONF_PORT	MACRO		    ;INICIALIZACION MACRO
	
    BANKSEL	ANSELH
    CLRF	ANSELH
    BANKSEL	TRISB
    MOVLW	b'00111000'
    MOVWF	TRISB
    MOVWF	WPUB		    
    MOVWF	IOCB
    CLRF	TRISC
    
    ENDM			    ;FINALIZACION MACRO
    
    
;CONFIGURACION TMRO
    
CONF_TMR0	MACRO
    BANKSEL	OPTION_REG
    MOVLW	b'00000111'
    MOVWF	OPTION_REG
    BANKSEL	TMR0
    MOVLW	.61
    MOVWF	TMR0
    
    ENDM
	

;CONFIGURACION INT
    
    CONF_INT	MACRO
    BANKSEL	INTCON
    MOVLW	b'10101000'
    MOVWF	INTCON
    
    ENDM
    
;CONFIGURACION INIT REGISTRO
    
INICIO	
    CONF_PORT
    CONF_TMR0
    CONF_INT
    
    GOTO	$
    
;CONFIGURACION ISR_INICIO
    
ISR_INICIO
    
    ;SALVADO CONTEXTO-----------------------
    MOVWF	W_TEMP
    SWAPF	STATUS, W
    MOVWF	STATUS_TEMP
    
    ;ISR CONTENIDO
    BTFSC	INTCON, TOIF	    ;SALTAR SI ES 0, TESTEAMOS EL INTCONT TOIF POR EL TEMA DE TESTEAR EL TIEMPO
    GOTO	ISR_TEMP_TMR0	    
    GOTO	ISR_FIN	
    
    
ISR_TEMP_TMR0
    INCF	COUNT_TMR0, F
    MOVLW	.250
    SUBWF	COUNT_TMR0, W
    BTFSS	STATUS, Z	    ;TESTEO LA CANTIDAD DE DESBORDES
    GOTO	ISR_TMR0	    
    GOTO	ISR_TECLA	    ;
    
    
ISR_TMR0
    MOVLW	.61		    ;EL TIMER 0 ARRANCA A CONTAR EN 61, ESTO ES LO QUE ME DICE
    MOVWF	TMR0
    GOTO	ISR_FIN
    
ISR_TECLA_TEST
    BTFSC	INTCON, RBIO
    CALL	ISR_TECLA
    GOTO	ISR_FIN
    
ISR_FIN
    BCF		INTCON,	TOIF
    BCF		INTCON,	RBIF
    BCF		STATUS, RB0
    BCF		STATUS, RB1  
    MOVF	NTecla, W
    CALL	TABLA_DECO_CC
    MOVWF	PORTC
    
    ;RECONSTRUCCION CONTEXTO----------------
    SWAPF	STATUS_TEMP, W
    MOVWF	STATUS
    SWAPF	W_TEMP, F
    SWAPF	W_TEMP, W
    RETFIE	
    
TABLA_DECO_CC
    ADDWF	PCL, F		    ;TABLA, COLOCAMOS LOS VALORES AHI ABAJO Y LISTAKI, SE DEVUELVE AL MEJOR ESTILO TABLA
    RETFW	0x3F
    
NTecla
    1
    2
    3
    4
    5
    6
    7
    8
    9
    
    
    
    
    END				    ;FINALIZACION PROGRAMA
    