;Encabezado
LIST P=16F887
#include "p16f887.inc"
    
__CONFIG _CONFIG1, _WDT_OFF
    
    
;DEFINICION VARIABLES
	    CBLOCK	0x20
		    W_TEM
		    STATUS_TEMP
		    COUNT_TMRO
		    VAL_1
		    VAL_2
		    VAL_3
		    DELAY1
		    DELAY2
		    DELAY3
	    ENDC
    
	CONF_PUERTOS	    MACRO
	    BANKSEL	    ANSELH
	    CLRF	    ANSELH
	    BANKSEL	    PORTA
	    CLRF	    PORTA
	    CLRF	    PORTB
	    CLRF	    PORTC
	    CLRF	    PORTD
	    BANKSEL	    TRISB
	    CLRF	    TRISB
	    CLRF	    TRISA
	    CLRF	    TRISD
	    MOVLW	    b'10000000'
	    MOVWF	    TRISC
	ENDM
    
	CONF_INICIAL_SERIAL	MACRO
	    BANKSEL	    BAUDCTL
	    BSF		    BAUDCTL, BRG16

	    BANKSEL	    TXSTA
	    BSF		    TXSTA, TXEN
	    BCF		    TXSTA, SYNC ; SER PARA BAUD RATE
	    BCF		    TXSTA, TX9
	    BSF		    TXSTA, BRGH ; SET PARA BAUD RATE
	    MOVLW	    .25
	    MOVWF	    SPBRG

	    BANKSEL	    RCSTA
	    BSF		    RCSTA, SPEN
	    BCF		    RCSTA, RX9
	    BSF		    RCSTA, CREN

	    BANKSEL	    PIE1	
	    BSF		    PIE1, RCIE	; HABILITACION DE INTERRUPCION POR RCIE CUANDO LLEGA UN DATO

	ENDM

	CONF_VARIABLES	    MACRO
	    MOVLW	    .4
	    MOVWF	    VAL_1
	    MOVLW	    .255
	    MOVWF	    VAL_2
	    MOVWF	    VAL_3
	ENDM

	;INICIO MICRO

	    ORG		    0x00
	    GOTO	    INICIO
	    ORG		    0x04
	    GOTO	    ISR_TEST
	    ORG		    0x05

	INICIO		    NOP
	    CONF_PUERTOS
	    CONF_INICIAL_SERIAL
	    CONF_VARIABLES
	    GOTO	ENVIO

	ISR_TEST	    NOP
	    BTFSC	    PIR1, RCIF
	    CALL	    REPRESENTACION_VALOR
	    GOTO	    ENVIO

	ENVIO
	    CALL	    RETARDO
	    CALL	    ENVIO_SERIE
	    GOTO	    ENVIO

	ENVIO_SERIE
	    BANKSEL	    TXSTA
	    BTFSS	    TXSTA, TRMT	
	    GOTO	    ENVIO_SERIE
	    BANKSEL	    TXREG
	    MOVLW	    .49
	    MOVWF	    TXREG
	    NOP
	    NOP
	    RETURN 

	REPRESENTACION_VALOR	NOP
	    BANKSEL	    PIR1
	    BCF		    PIR1, RCIF
	    
	    RETURN

	RETARDO
	    MOVF	    VAL_1, W
	    MOVWF	    DELAY1

	LOOP1	  
	    MOVF	    VAL_2, W
	    MOVWF	    DELAY2

	LOOP2
	    MOVF	    VAL_3, W
	    MOVWF	    DELAY3

	LOOP3
	    DECFSZ	    DELAY3, F
	    GOTO	    LOOP3
	    DECFSZ	    DELAY2, F
	    GOTO	    LOOP2
	    DECFSZ	    DELAY1, F
	    GOTO	    LOOP1
	    RETURN

	END